"""create_initial_tables

Revision ID: ef65c96e05df
Revises: 
Create Date: 2026-01-15 13:12:12.212089+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ef65c96e05df'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False, comment='Símbolo do ativo (ex: BTC, ETH)'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Nome completo (ex: Bitcoin, Ethereum)'),
    sa.Column('coingecko_id', sa.String(length=100), nullable=True, comment='ID no CoinGecko (ex: bitcoin, ethereum)'),
    sa.Column('binance_symbol', sa.String(length=20), nullable=True, comment='Par de trading na Binance (ex: BTCUSDT)'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Se o ativo está sendo monitorado'),
    sa.Column('priority', sa.Integer(), nullable=False, comment='Prioridade de monitoramento (maior = mais importante)'),
    sa.Column('description', sa.Text(), nullable=True, comment='Descrição do ativo'),
    sa.Column('logo_url', sa.String(length=500), nullable=True, comment='URL do logo'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_symbol'), 'assets', ['symbol'], unique=True)
    op.create_table('metric_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False, comment='Símbolo do ativo'),
    sa.Column('snapshot_date', sa.Date(), nullable=False, comment='Data do snapshot'),
    sa.Column('explosion_score_open', sa.Float(), nullable=True, comment='Score no início do dia'),
    sa.Column('explosion_score_high', sa.Float(), nullable=True, comment='Score máximo do dia'),
    sa.Column('explosion_score_low', sa.Float(), nullable=True, comment='Score mínimo do dia'),
    sa.Column('explosion_score_close', sa.Float(), nullable=True, comment='Score no final do dia'),
    sa.Column('price_open', sa.Float(), nullable=True),
    sa.Column('price_high', sa.Float(), nullable=True),
    sa.Column('price_low', sa.Float(), nullable=True),
    sa.Column('price_close', sa.Float(), nullable=True),
    sa.Column('price_change_pct', sa.Float(), nullable=True),
    sa.Column('volume_total', sa.Float(), nullable=True),
    sa.Column('volume_avg', sa.Float(), nullable=True),
    sa.Column('whale_transactions_count', sa.Integer(), nullable=False, comment='Número de transações de baleias'),
    sa.Column('whale_volume_total', sa.Float(), nullable=True, comment='Volume total de baleias (USD)'),
    sa.Column('exchange_netflow_total', sa.Float(), nullable=True, comment='Netflow total do dia'),
    sa.Column('alerts_count', sa.Integer(), nullable=False, comment='Número de alertas gerados'),
    sa.Column('full_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Dados completos em JSON'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metric_snapshots_snapshot_date'), 'metric_snapshots', ['snapshot_date'], unique=False)
    op.create_index(op.f('ix_metric_snapshots_symbol'), 'metric_snapshots', ['symbol'], unique=False)
    op.create_index('ix_metric_symbol_date', 'metric_snapshots', ['symbol', 'snapshot_date'], unique=True)
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('alert_type', sa.String(length=50), nullable=False, comment='Tipo: score_threshold, whale_activity, sudden_change, volume_spike'),
    sa.Column('severity', sa.String(length=20), nullable=False, comment='Severidade: info, warning, critical'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='Título do alerta'),
    sa.Column('message', sa.Text(), nullable=False, comment='Mensagem detalhada'),
    sa.Column('trigger_value', sa.Float(), nullable=True, comment='Valor que disparou o alerta'),
    sa.Column('trigger_reason', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Detalhes do motivo em JSON'),
    sa.Column('score_at_trigger', sa.Float(), nullable=True, comment='Score no momento do alerta'),
    sa.Column('price_at_trigger', sa.Float(), nullable=True, comment='Preço no momento do alerta'),
    sa.Column('is_read', sa.Boolean(), nullable=False, comment='Se o alerta foi lido'),
    sa.Column('is_dismissed', sa.Boolean(), nullable=False, comment='Se o alerta foi dispensado'),
    sa.Column('read_at', sa.DateTime(), nullable=True, comment='Momento em que foi lido'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_alerts_asset_created', 'alerts', ['asset_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_alerts_asset_id'), 'alerts', ['asset_id'], unique=False)
    op.create_index(op.f('ix_alerts_created_at'), 'alerts', ['created_at'], unique=False)
    op.create_index('ix_alerts_unread', 'alerts', ['is_read', 'created_at'], unique=False)
    op.create_table('asset_scores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('explosion_score', sa.Float(), nullable=False, comment='Score de explosão (0-100)'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='Status: low, attention, high'),
    sa.Column('whale_accumulation_score', sa.Float(), nullable=False, comment='Score de acumulação de baleias (0-100)'),
    sa.Column('exchange_netflow_score', sa.Float(), nullable=False, comment='Score de fluxo líquido de exchanges (0-100)'),
    sa.Column('volume_anomaly_score', sa.Float(), nullable=False, comment='Score de anomalia de volume (0-100)'),
    sa.Column('oi_pressure_score', sa.Float(), nullable=False, comment='Score de pressão de Open Interest (0-100)'),
    sa.Column('narrative_momentum_score', sa.Float(), nullable=False, comment='Score de momentum de narrativa (0-100)'),
    sa.Column('price_usd', sa.Float(), nullable=True, comment='Preço em USD no momento do cálculo'),
    sa.Column('price_change_24h', sa.Float(), nullable=True, comment='Variação de preço em 24h (%)'),
    sa.Column('volume_24h', sa.Float(), nullable=True, comment='Volume em 24h (USD)'),
    sa.Column('calculation_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Detalhes do cálculo em JSON'),
    sa.Column('main_drivers', sa.Text(), nullable=True, comment='Principais fatores do score'),
    sa.Column('calculated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_scores_asset_id'), 'asset_scores', ['asset_id'], unique=False)
    op.create_index('ix_asset_scores_asset_timestamp', 'asset_scores', ['asset_id', 'calculated_at'], unique=False)
    op.create_index(op.f('ix_asset_scores_calculated_at'), 'asset_scores', ['calculated_at'], unique=False)
    op.create_index('ix_asset_scores_explosion', 'asset_scores', ['explosion_score'], unique=False)
    op.create_table('exchange_flows',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('inflow', sa.Float(), nullable=False, comment='Volume entrando em exchanges (USD)'),
    sa.Column('outflow', sa.Float(), nullable=False, comment='Volume saindo de exchanges (USD)'),
    sa.Column('netflow', sa.Float(), nullable=False, comment='Fluxo líquido (inflow - outflow). Negativo = saída'),
    sa.Column('exchange', sa.String(length=50), nullable=True, comment="Exchange específica ou 'all' para agregado"),
    sa.Column('timeframe', sa.String(length=10), nullable=False, comment='Período: 1h, 24h, 7d'),
    sa.Column('source', sa.String(length=50), nullable=True, comment='Fonte dos dados: glassnode, cryptoquant, etc'),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Dados brutos da API'),
    sa.Column('timestamp', sa.DateTime(), nullable=False, comment='Momento da medição'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_exchange_flow_asset_time', 'exchange_flows', ['asset_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_exchange_flows_asset_id'), 'exchange_flows', ['asset_id'], unique=False)
    op.create_index(op.f('ix_exchange_flows_timestamp'), 'exchange_flows', ['timestamp'], unique=False)
    op.create_table('narrative_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False, comment='Título da notícia/evento'),
    sa.Column('summary', sa.Text(), nullable=True, comment='Resumo do conteúdo'),
    sa.Column('url', sa.String(length=1000), nullable=True, comment='URL da fonte'),
    sa.Column('source', sa.String(length=100), nullable=False, comment='Fonte: cryptopanic, twitter, manual, etc'),
    sa.Column('event_type', sa.String(length=50), nullable=False, comment='Tipo: news, announcement, regulation, hack, listing, etc'),
    sa.Column('sentiment', sa.String(length=20), nullable=False, comment='Sentimento: positive, negative, neutral'),
    sa.Column('sentiment_score', sa.Float(), nullable=False, comment='Score de sentimento (-1 a 1)'),
    sa.Column('importance', sa.String(length=20), nullable=False, comment='Importância: low, medium, high, critical'),
    sa.Column('tags', postgresql.ARRAY(sa.String(length=50)), nullable=True, comment='Tags relacionadas'),
    sa.Column('mentioned_assets', postgresql.ARRAY(sa.String(length=20)), nullable=True, comment='Símbolos de ativos mencionados'),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Dados brutos da API'),
    sa.Column('published_at', sa.DateTime(), nullable=False, comment='Data de publicação'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_narrative_events_asset_id'), 'narrative_events', ['asset_id'], unique=False)
    op.create_index(op.f('ix_narrative_events_published_at'), 'narrative_events', ['published_at'], unique=False)
    op.create_index('ix_narrative_published', 'narrative_events', ['published_at'], unique=False)
    op.create_index('ix_narrative_sentiment', 'narrative_events', ['sentiment_score'], unique=False)
    op.create_table('price_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False, comment='Volume em USD'),
    sa.Column('timeframe', sa.String(length=10), nullable=False, comment='Timeframe: 1m, 5m, 15m, 1h, 4h, 1d'),
    sa.Column('source', sa.String(length=50), nullable=False, comment='Fonte: binance, coingecko, etc'),
    sa.Column('timestamp', sa.DateTime(), nullable=False, comment='Abertura do candle'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_price_asset_time', 'price_data', ['asset_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_price_data_asset_id'), 'price_data', ['asset_id'], unique=False)
    op.create_index(op.f('ix_price_data_timestamp'), 'price_data', ['timestamp'], unique=False)
    op.create_index('ix_price_timeframe', 'price_data', ['timeframe', 'timestamp'], unique=False)
    op.create_table('whale_transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('tx_hash', sa.String(length=100), nullable=True, comment='Hash da transação'),
    sa.Column('amount', sa.Float(), nullable=False, comment='Quantidade do ativo'),
    sa.Column('amount_usd', sa.Float(), nullable=False, comment='Valor em USD'),
    sa.Column('transaction_type', sa.String(length=50), nullable=False, comment='Tipo: exchange_deposit, exchange_withdrawal, unknown_transfer, etc'),
    sa.Column('from_address', sa.String(length=100), nullable=True, comment='Endereço de origem'),
    sa.Column('from_owner', sa.String(length=100), nullable=True, comment='Dono do endereço de origem (ex: binance, unknown)'),
    sa.Column('to_address', sa.String(length=100), nullable=True, comment='Endereço de destino'),
    sa.Column('to_owner', sa.String(length=100), nullable=True, comment='Dono do endereço de destino'),
    sa.Column('blockchain', sa.String(length=50), nullable=True, comment='Blockchain da transação'),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Dados brutos da API'),
    sa.Column('timestamp', sa.DateTime(), nullable=False, comment='Momento da transação'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tx_hash')
    )
    op.create_index(op.f('ix_whale_transactions_asset_id'), 'whale_transactions', ['asset_id'], unique=False)
    op.create_index(op.f('ix_whale_transactions_timestamp'), 'whale_transactions', ['timestamp'], unique=False)
    op.create_index('ix_whale_tx_asset_time', 'whale_transactions', ['asset_id', 'timestamp'], unique=False)
    op.create_index('ix_whale_tx_type', 'whale_transactions', ['transaction_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_whale_tx_type', table_name='whale_transactions')
    op.drop_index('ix_whale_tx_asset_time', table_name='whale_transactions')
    op.drop_index(op.f('ix_whale_transactions_timestamp'), table_name='whale_transactions')
    op.drop_index(op.f('ix_whale_transactions_asset_id'), table_name='whale_transactions')
    op.drop_table('whale_transactions')
    op.drop_index('ix_price_timeframe', table_name='price_data')
    op.drop_index(op.f('ix_price_data_timestamp'), table_name='price_data')
    op.drop_index(op.f('ix_price_data_asset_id'), table_name='price_data')
    op.drop_index('ix_price_asset_time', table_name='price_data')
    op.drop_table('price_data')
    op.drop_index('ix_narrative_sentiment', table_name='narrative_events')
    op.drop_index('ix_narrative_published', table_name='narrative_events')
    op.drop_index(op.f('ix_narrative_events_published_at'), table_name='narrative_events')
    op.drop_index(op.f('ix_narrative_events_asset_id'), table_name='narrative_events')
    op.drop_table('narrative_events')
    op.drop_index(op.f('ix_exchange_flows_timestamp'), table_name='exchange_flows')
    op.drop_index(op.f('ix_exchange_flows_asset_id'), table_name='exchange_flows')
    op.drop_index('ix_exchange_flow_asset_time', table_name='exchange_flows')
    op.drop_table('exchange_flows')
    op.drop_index('ix_asset_scores_explosion', table_name='asset_scores')
    op.drop_index(op.f('ix_asset_scores_calculated_at'), table_name='asset_scores')
    op.drop_index('ix_asset_scores_asset_timestamp', table_name='asset_scores')
    op.drop_index(op.f('ix_asset_scores_asset_id'), table_name='asset_scores')
    op.drop_table('asset_scores')
    op.drop_index('ix_alerts_unread', table_name='alerts')
    op.drop_index(op.f('ix_alerts_created_at'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_asset_id'), table_name='alerts')
    op.drop_index('ix_alerts_asset_created', table_name='alerts')
    op.drop_table('alerts')
    op.drop_index('ix_metric_symbol_date', table_name='metric_snapshots')
    op.drop_index(op.f('ix_metric_snapshots_symbol'), table_name='metric_snapshots')
    op.drop_index(op.f('ix_metric_snapshots_snapshot_date'), table_name='metric_snapshots')
    op.drop_table('metric_snapshots')
    op.drop_index(op.f('ix_assets_symbol'), table_name='assets')
    op.drop_table('assets')
    # ### end Alembic commands ###
